# This file seems to be needed only for bazel's dependency pinning to figure out
# declared dependencies, actual build rules are in BUILD.bazel.

[package]
name = "fontations_bridge"
edition = "2021"
version = "0.1.0"

[dependencies]
read-fonts = "0.11"
font-types = "0.4"
skrifa = "0.10"
cxx = "1.0.107"

[lib]
name = "fontations_ffi"
path = "src/ffi.rs"
