# This file seems to be needed only for bazel's dependency pinning to figure out
# declared dependencies, actual build rules are in BUILD.bazel.

[package]
name = "fontations"
edition = "2021"
version = "0.1.0"

[dependencies]
read-fonts = "0.19"
font-types = "0.5"
skrifa = "0.19.2"
bytemuck = "1.16"
cxx = "1.0"

[lib]
name = "fontations_ffi"
path = "src/ffi.rs"
